# These are supported funding model platforms

github: gioxx
patreon: gioxx
custom: ["https://www.paypal.me/gioxx", PayPal]
custom: ["https://tag.satispay.com/gioxx", Satispay]
custom: ["https://www.buymeacoffee.com/gioxx", Buy me a coffee]
custom: ["https://go.gioxx.org/acquista", Acquista su Amazon]
